Adding solution for lab2
g-xander/nsu-sdt2020 pull request #2
Opened 2020-10-13 17:57 UTC by g-xander

Initial solution for lab2

Open for comments.

2020-10-23 21:09 UTC, shishkin-pavel requested changes

2020-10-23 21:09 UTC, shishkin-pavel commented on labs/lab2/src/lab2/part2.clj
> +                    (first (nth wrap (- steps 1)))
а если мы хотим посчитать интеграл от нуля до нуля?

2020-10-23 21:09 UTC, shishkin-pavel commented on labs/lab2/src/lab2/part2.clj
> +            (float (+
зачем везде конвертировать человеческие дроби во флоаты? =)

2020-10-24 00:56 UTC, g-xander commented on labs/lab2/src/lab2/part2.clj
> +            (float (+
Просто иррациональное число  выглядит "лучше" в тестах, чем неправильная дробь...

2020-10-24 01:03 UTC, g-xander commented on labs/lab2/src/lab2/part2.clj
> +                    (first (nth wrap (- steps 1)))
ок

2020-10-24 05:57 UTC, g-xander commented on labs/lab2/src/lab2/part2.clj
> +            (float (+
Точнее `(println 100/21)` в output будет выглядеть как `100/21`, а `(println (float 100/21))` => `4.7619047`, что помогает при проверке правильности вычислений интеграла при его разработке.

2020-10-30 22:56 UTC, shishkin-pavel approved these changes
бывают всякие лишние скобочки или слишком сложные записи, ну да ладно

2020-10-31 01:52 UTC, merged